name: upload extension to github artifacts

on:
  push:
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack enable npm pnpm
      - run: pnpm install
      - run: pnpm build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r extension.zip dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}